Traceback (most recent call last):
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/cd96/psi4conda/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
File          ='.\\response_1679606406055_H2O_GFNFF.json'
H2_O_GFNFF    =LoadData(File)
File         ='.\\response_1679607003317_H2O_GFN1xTB.json'
H2_O_GFN1xTB =LoadData(File)
File         = '.\\response_1679607376257_H2O_GFN2xTB.json'
H2_O_GFN2xTB =LoadData(File)
File         ='.\\H2_O_exp.csv'
H2_O_exp     = IR_exp(File)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m File          [38;5;241m=[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;130;01m\\[39;00m[38;5;124mresponse_1679606406055_H2O_GFNFF.json[39m[38;5;124m'[39m
[0;32m----> 2[0m H2_O_GFNFF    [38;5;241m=[39m[43mLoadData[49m[43m([49m[43mFile[49m[43m)[49m
[1;32m      3[0m File         [38;5;241m=[39m[38;5;124m'[39m[38;5;124m.[39m[38;5;130;01m\\[39;00m[38;5;124mresponse_1679607003317_H2O_GFN1xTB.json[39m[38;5;124m'[39m
[1;32m      4[0m H2_O_GFN1xTB [38;5;241m=[39mLoadData(File)

Cell [0;32mIn[2], line 2[0m, in [0;36mLoadData[0;34m(File)[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mLoadData[39m(File):
[0;32m----> 2[0m     File_open[38;5;241m=[39m[38;5;28;43mopen[39;49m[43m([49m[43mFile[49m[43m)[49m
[1;32m      3[0m     File_loaded [38;5;241m=[39m json[38;5;241m.[39mload(File_open)
[1;32m      4[0m     Dic [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mFile[39m[38;5;124m"[39m: File,
[1;32m      5[0m            [38;5;124m"[39m[38;5;124mwavenumbers[39m[38;5;124m"[39m   : File_loaded[[38;5;124m'[39m[38;5;124mwavenumbers[39m[38;5;124m'[39m],
[1;32m      6[0m            [38;5;124m"[39m[38;5;124mintensities[39m[38;5;124m"[39m  : File_loaded[[38;5;124m'[39m[38;5;124mintensities[39m[38;5;124m'[39m]
[1;32m      7[0m            }

File [0;32m~/psi4conda/envs/jbook/lib/python3.11/site-packages/IPython/core/interactiveshell.py:284[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    277[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    278[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    279[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    280[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    281[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    282[0m     )
[0;32m--> 284[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '.\\response_1679606406055_H2O_GFNFF.json'

